name: UpgradePlugin
version: 1.0
author: dagxam
main: ru.dagxam.upgradeplugin.UpgradePlugin
api-version: '1.21'

commands:
  giveupgradebook:
    description: Выдает Книгу Улучшения.
    # ИЗМЕНЕНО: Обновляем usage
    usage: /<command> <имя> <количество>
    permission: upgradeplugin.givebook

permissions:
  upgradeplugin.givebook:
    description: Дает право на использование команды /giveupgradebook.
    default: op
